# -*- coding: utf-8 -*-
"""ML-HW0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5JCiM_BKIC5qYMA9Nf9_RWT6AxZ_pvp
"""

import numpy as np
#considering a random array for the questions provided
X = [[1,2,3], [4,5,6], [7,8,9]]
X = np.array(X)
print(X)

def extract_odd_numbers(x):
 #first the list is converted to a numpy array
  odd_numbers = []
  odd_numbers = np.array(odd_numbers, dtype = 'i')
  print(odd_numbers)
  x = np.array(x)
  x = x.flatten()
  print(x)
  for element in x:
    #print(element)
    if element%2 == 1:
      odd_numbers = np.append(odd_numbers, element)

  return odd_numbers

odd_numbers = []
odd_numbers = extract_odd_numbers(X)
print(odd_numbers)

def make_funny_matrix(N):
  matrix = np.array([], dtype = 'i')
  for i in range(N):
    row = np.array([], dtype = 'i')
    for j in range(N):
      row = np.append(row, j+1)

    if(matrix.size == 0):
      matrix = np.append(matrix, row)
    else:
     matrix = np.row_stack([matrix, row])

  return matrix

#trying to generate the funny matrix for n = 6
n =  6

matrix = make_funny_matrix(n)
print(matrix)

A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(A)
print(A.size)
print(A[0].size)
print(A.size//A[0].size)
#m -> no. of rows
#n -> no.of columns
m = A.size//A[0].size
n = A[0].size

first = A[0]
first = np.append(first, [1])
print(first)

def append_ones_column(A):
  #m -> no. of rows
  #n -> no.of columns
  matrix = np.array([], dtype = 'i')
  m = A.size//A[0].size
  n = A[0].size
  first_row = True
  for i in range(m):
    row = A[i]
    row = np.append(row, [1])
    if(first_row == True):
      matrix = np.append(matrix, row)
      first_row = False
    else:
      matrix = np.row_stack([matrix, row])
  return matrix

matrix = append_ones_column(A)
print(matrix)